### ISSUE TITLE
bug: `PathNotFoundException` when running `coverde report`

### ISSUE THREAD

**Issue by mrverdant13** [mrverdant13/coverde#73]
> Hi Karlo
> 
> I'm so sorry to bother you...  I have installed the latest version of
> `coverde` and I have added melos scripts as you suggested.  Below is what I
> have:
> 
> melos exec --file-exists=coverage/lcov.info -- coverde filter -i ./coverage/
> lcov.info -o MELOS_ROOT_PATH/coverage/base.lcov.info --filters='\.g\.dart'
> --paths-parent=MELOS_PACKAGE_PATH
> coverde report -i MELOS_ROOT_PATH/coverage/base.lcov.info --medium 50
> --high 80
> 
> I can see that the my base.lcov.info file now has paths like so:
> 
> SF:/Users/shane/Woolworths/WooliesGO/driver_app_flutter/domain/lib/src/models/configuration/driver_break_timer.dart
> DA:7,0
> DA:15,0
> DA:16,0
> LF:3
> LH:0
> end_of_record
> SF:/Users/shane/Woolworths/WooliesGO/driver_app_flutter/domain/lib/src/models/configuration/live_location.dart
> DA:7,0
> DA:21,0
> DA:23,0
> DA:24,0
> DA:26,0
> LF:5
> LH:0
> end_of_record
> 
> 
> But when it runs "coverde report -i MELOS_ROOT_PATH/coverage/base.lcov.info
> --medium 50 --high 80" I still see errors?  I'm seeing
> "PathNotFoundException: Cannot open file, path =
> 'Users/shane/Woolworths/WooliesGO/driver_app_flutter/domain/lib/src/models/configuration/driver_break_timer.dart'
> (OS Error: No such file or directory, errno = 2)"
> 
> The part that confuses me is that those files are definitely there in that
> directory.  I can see them!  I was hoping you might be able to help?
> Coverde is awesome - we would love to keep using it!
> 
> Thanks
> Shane
> 
> 

_Originally posted by @shane-henderson-308 in https://github.com/mrverdant13/coverde/issues/68#issuecomment-1685526845_

**Comment by mrverdant13** [comment]
> Hey again, @shane-henderson-308 👋🏼
> 
> Well, I feel the issue is related to the prefix path. I believe you are on a Windows PC with WSL, right? The `Users/` folder should be under a root drive, e.g. `C:/`, `D:/`, or so.
> 
> If that is not the case, I would appreciate it if you could give more context on your OS, Dart version, or any additional details that might be handy to consider when debugging this.
> 
> PS1: The `coverde` CLI itself uses `melos`, you can check the `melos.yaml` file in the root as reference. PS2: Please consider also providing formatted code.

_Originally posted by @mrverdant13 in https://github.com/mrverdant13/coverde/issues/68#issuecomment-1685607094_

**Comment by mrverdant13** [comment]
> Hi Karlo
> 
> Absolutely - anything I can provide you with which might help, please just
> ask.
> 
> I am using a: *MacBook Pro (M2)* running *13.4.1 (c)*.
> 
> My dart version is:
> Dart SDK version: 3.0.0 (stable) (Thu May 4 01:11:00 2023 -0700) on
> "macos_arm64"
> 
> The path I'm using is a pretty standard Mac path, which is:
> */Users/shane/*Woolworths/WooliesGO/driver_app_flutter
> 
> I have attached the `melos.yaml` file and `melos_driver_app_flutter.iml` in
> case either of those help.
> 
> As I said, please let me know if there is anything else I can do to try and
> help.
> 
> Shane




_Originally posted by @shane-henderson-308 in https://github.com/mrverdant13/coverde/issues/68#issuecomment-1685615380_

**Comment by mrverdant13** [comment]
Thanks, @shane-henderson-308
Will check this and let you know on any update.

**Comment by kinyoklion** [comment]
I also see this on Ubuntu. Using it with melos with the merge coverage example from the readme.

It seems to not include the root '/' of the path.

```
PathNotFoundException: Cannot open file, path = 'home/rlamb/code/launchdarkly/flutter-client-sdk-rewrite-private/packages/client/lib/src/flag_manager/context_index.dart' (OS Error: No such file or directory, errno = 2)
```

**Comment by kinyoklion** [comment]
I've noticed that the original coverage files have relative paths, and the combined file has full paths. It looks like maybe the canonicalization code expects them to be relative?

**Comment by mrverdant13** [comment]
Hey, @shane-henderson-308 @kinyoklion 👋🏼
Thanks for your patience

I have reworked the way source file paths are manipulated by the CLI
Hopefully, those changes address your issues

---

As a side note, I am considering implementing some E2E tests for some common workflows.
It would be handy to know the regular sequence of actions that you perform when dealing with trace files (lcov).

**Comment by kinyoklion** [comment]
Hello @mrverdant13,

Thank you for fixing this. I tested it out this morning and things are working well.

> It would be handy to know the regular sequence of actions that you perform when dealing with trace files (lcov).

There are only a couple things I'm currently doing with the tracefiles. I am working on a re-write of a project into a dart/flutter mono repo and I am using melos. 

I execute the tests, then for CI generate a basic coverage report (which will likely be accompanies by a threshold check at some point). For local development I like generating an HTML report.

Snippets from the melos configuration.
```  
test:
    # Add more packages as more of them have tests.
    # Tests are ran with flutter as it supports coverage. Some packages may also include flutter
    # dependencies.
    run: MELOS_PACKAGES="launchdarkly_dart_common" melos exec -- flutter test . --coverage

  merge-trace-files:
    description: Merge all packages coverage trace files ignoring data related to generated files.
    run: >
      coverde rm MELOS_ROOT_PATH/coverage/filtered.lcov.info &&
      melos exec --file-exists=coverage/lcov.info -- "coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --paths-parent MELOS_PACKAGE_PATH --filters '\.g\.dart'"

  coverage-report:
    run: >
      melos run merge-trace-files &&
      coverde value -i coverage/filtered.lcov.info

  coverage-report-html:
    run: >
      melos run merge-trace-files &&
      coverde report -i coverage/filtered.lcov.info -o coverage/html/
```

Thank you,
Ryan
